### PR TITLE
tgz: removed 'false' parameter for fastFetchQuery

### PR DESCRIPTION
**Pull request by tgehrsitz-ite**

### CODE REVIEW

**Comment by zeroWiNNeR** [comment]
Hi! Could u please update ur branch for this PR

**Comment by tgehrsitz-ite** [comment]
Hi, okay, done.

**Comment by bostandyksoft** [comment]
Hi. How long PR can waits approval?

**Review by filipelautert — APPROVED** [review]
Sorry for the delay to review this @tgehrsitz-ite . Thanks for the PR!

**Comment by tgehrsitz-ite** [comment]
No worries, thanks for the review!

**Pull request merged**
